version: "3"
services:
  java:
    build:
      context: .
    container_name: cube_java_springboot
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:./opentelemetry-javaagent.jar
      - OTEL_SERVICE_NAME=cube_sample_java_spring_boot_otel
      - OTEL_EXPORTER_OTLP_COMPRESSION=gzip
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf

      # capture jvm non-heap buffer pool metrics
      - OTEL_INSTRUMENTATION_RUNTIME_TELEMETRY_JAVA17_ENABLE_ALL=true

      # optional settings
      - OTEL_RESOURCE_ATTRIBUTES=cube.environment=UNSET,service.version=1.2.3,mykey1=myvalue1,mykey2=myvalue2

      # enable debug mode
      # - OTEL_JAVAAGENT_DEBUG=true

      # print traces on console
      - OTEL_TRACES_EXPORTER=console
      # send traces to CubeAPM
      # - OTEL_TRACES_EXPORTER=otlp
      # - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://host.docker.internal:4318/v1/traces

      # print metrics on console
      - OTEL_METRICS_EXPORTER=console
      # send metrics to CubeAPM
      # - OTEL_METRICS_EXPORTER=otlp
      # - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://host.docker.internal:3130/api/metrics/v1/save/otlp

      # print logs on console
      - OTEL_LOGS_EXPORTER=console
      # send logs to CubeAPM
      # - OTEL_LOGS_EXPORTER=otlp
      # - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://host.docker.internal:3130/api/logs/insert/opentelemetry/v1/logs
      # - OTEL_EXPORTER_OTLP_LOGS_HEADERS=Cube-Stream-Fields=service.name%2Cseverity
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    restart: always

  mysql:
    image: mysql:8.0
    container_name: cube_java_springboot_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - cube_java_springboot_mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine3.18
    container_name: cube_java_springboot_redis

volumes:
  cube_java_springboot_mysql:
