version: "3"
services:
  java:
    build:
      context: .
    container_name: cube_java_springboot
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:./opentelemetry-javaagent.jar
      - OTEL_SERVICE_NAME=cube_sample_java_spring_boot_otel
      - OTEL_EXPORTER_OTLP_COMPRESSION=gzip
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf

      # print traces on console
      - OTEL_JAVAAGENT_DEBUG=true
      
      # send traces to CubeAPM
      # - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://host.docker.internal:4318/v1/traces
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    restart: always

  mysql:
    image: mysql:8.0
    container_name: cube_java_springboot_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - cube_java_springboot_mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine3.18
    container_name: cube_java_springboot_redis

volumes:
  cube_java_springboot_mysql:
