#mysql
spring.datasource.url=jdbc:mysql://cube_java_springboot_mysql:3306/test?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
# spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



# Redis Config
spring.cache.type=redis
spring.data.redis.host=cube_java_springboot_redis
spring.data.redis.port=6379

# RabbitMQ Config
spring.rabbitmq.host=cube_java_springboot_rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
rabbitmq.exchange=sample.topic.exchange
rabbitmq.queue=sample.topic.queue
rabbitmq.routing-key=sample.topic.key

server.port=8000