#!/usr/bin/env python3
"""Render tmp/docker-compose.host.yml from docker-compose.yml (host network).

Compose overlay !reset is ignored by some compose v2 builds, which then rejects
network_mode + networks. This writes a standalone file with no networks/ports.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys

HOSTS = [
    "mysql-host:127.0.0.1",
    "postgres-host:127.0.0.1",
    "redis-host:127.0.0.1",
    "kafka-host:127.0.0.1",
    "rabbitmq-host:127.0.0.1",
    "java-host:127.0.0.1",
    "node-host:127.0.0.1",
    "python-host:127.0.0.1",
    "php-host:127.0.0.1",
    "dotnet-host:127.0.0.1",
    "datadog-agent:127.0.0.1",
    "kafka:127.0.0.1",
    "host.docker.internal:host-gateway",
]

KAFKA_ENV = {
    "KAFKA_ADVERTISED_LISTENERS": "PLAINTEXT://127.0.0.1:29092,PLAINTEXT_HOST://127.0.0.1:9092",
    "KAFKA_LISTENERS": "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092",
    "KAFKA_CONTROLLER_QUORUM_VOTERS": "1@127.0.0.1:29093",
}

# Host net uses the VM hostname (e.g. cursor); Erlang needs a stable local node.
RABBIT_ENV = {
    "RABBITMQ_NODENAME": "rabbit@localhost",
    "RABBITMQ_ERLANG_COOKIE": "cube-sample",
}


def yscalar(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)) and not isinstance(v, bool):
        return str(v)
    return json.dumps(str(v), ensure_ascii=False)


def ydump(obj, indent=0):
    sp = "  " * indent
    if isinstance(obj, dict):
        if not obj:
            return sp + "{}"
        lines = []
        for k, v in obj.items():
            key = str(k)
            if isinstance(v, dict):
                if not v:
                    lines.append(f"{sp}{key}: {{}}")
                else:
                    lines.append(f"{sp}{key}:")
                    lines.append(ydump(v, indent + 1))
            elif isinstance(v, list):
                if not v:
                    lines.append(f"{sp}{key}: []")
                else:
                    lines.append(f"{sp}{key}:")
                    lines.append(ydump(v, indent + 1))
            else:
                lines.append(f"{sp}{key}: {yscalar(v)}")
        return "\n".join(lines)
    if isinstance(obj, list):
        lines = []
        for item in obj:
            if isinstance(item, (dict, list)):
                lines.append(f"{sp}-")
                dumped = ydump(item, indent + 1)
                lines.append(dumped)
            else:
                lines.append(f"{sp}- {yscalar(item)}")
        return "\n".join(lines)
    return sp + yscalar(obj)


def env_to_dict(env):
    if env is None:
        return {}
    if isinstance(env, dict):
        return {str(k): ("" if v is None else str(v)) for k, v in env.items()}
    out = {}
    for item in env:
        if isinstance(item, str) and "=" in item:
            k, v = item.split("=", 1)
            out[k] = v
        elif isinstance(item, str):
            out[item] = ""
    return out


def extra_hosts_list(existing):
    seen = {}
    for entry in HOSTS:
        name, ip = entry.split(":", 1)
        seen[name] = ip
    if isinstance(existing, dict):
        for name, ip in existing.items():
            if name not in seen:
                seen[name] = str(ip)
    elif isinstance(existing, list):
        for item in existing:
            if isinstance(item, str) and ":" in item:
                name, ip = item.split(":", 1)
                if name not in seen:
                    seen[name] = ip
    return [f"{n}:{i}" for n, i in seen.items()]


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()
    src = os.path.join(root, "docker-compose.yml")
    dest = os.path.join(root, "tmp", "docker-compose.host.yml")
    env = os.environ.copy()
    env.pop("COMPOSE_FILE", None)
    raw = subprocess.check_output(
        ["docker", "compose", "-f", src, "config", "--format", "json"],
        cwd=root,
        env=env,
    )
    cfg = json.loads(raw)
    for name, svc in list(cfg.get("services", {}).items()):
        svc.pop("networks", None)
        svc.pop("ports", None)
        svc["network_mode"] = "host"
        svc["extra_hosts"] = extra_hosts_list(svc.get("extra_hosts"))
        if name == "kafka":
            envd = env_to_dict(svc.get("environment"))
            envd.update(KAFKA_ENV)
            svc["environment"] = envd
        if name == "rabbitmq":
            envd = env_to_dict(svc.get("environment"))
            envd.update(RABBIT_ENV)
            svc["environment"] = envd
            # rabbitmq-diagnostics during boot races the cookie (eacces) and
            # kills the broker. stack.sh already waits on AMQP publish.
            svc.pop("healthcheck", None)
    cfg.pop("networks", None)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    header = (
        "# Generated by scripts/render-host-compose.py — do not edit.\n"
        "# All services use network_mode: host (nested Docker user-bridge has no egress).\n"
    )
    with open(dest, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(ydump(cfg))
        f.write("\n")
    print(f"wrote {dest}")


if __name__ == "__main__":
    main()
